# Generated by Django 2.2.6 on 2020-04-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('foto_perfil', models.ImageField(max_length=200, upload_to='perfil/', verbose_name='Foto de Perfil')),
                ('foto_portada', models.ImageField(max_length=200, upload_to='portada/', verbose_name='Foto de Portada')),
                ('fecha_nacimiento', models.DateField(auto_now=True, verbose_name='Fecha de Nacimiento')),
                ('activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
        ),
    ]
